apiVersion: v1
kind: Service
metadata:
  name: {{ include "redirection-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redirection-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "redirection-operator.selectorLabels" . | nindent 4 }}